export enum SubscriberStatus {
    ALL = 'ALL',
    ACTIVE = 'ACTIVE',
    DEACTIVATED = 'DEACTIVATED',
    TEMP_SUSPENSION = 'TEMP_SUSPENSION',
    PENDING = 'PENDING',
    WRITTEN_OFF = 'WRITTEN_OFF',
    CANCELLED = 'CANCELLED',
    BLACKLISTED = 'BLACKLISTED',
    PARTIAL_DUNNED = 'PARTIAL_DUNNED'
}
